# -*- coding: utf-8 -*-
# === Unit test for the scaler stats ===
# Author: Kian Lewis
# Description: unit tests the scaler stats generated by the model
#

import json
import sys
import unittest
import tempfile
import subprocess
from pathlib import Path
import numpy as np
from sklearn.preprocessing import StandardScaler

class TestScalerStats(unittest.TestCase):

    def test_scaler_stats(self):
        # Temporary directory for the test
        with tempfile.TemporaryDirectory() as temp_dir:
            temp_path = Path(temp_dir)
            test_htdocs = temp_path / "htdocs"
            test_htdocs.mkdir()

            # create fake gesture samples for unit test
            test_gmap = {"1000": "TTS", "1001": "Unit", "1002": "Test"}
            with open(test_htdocs / "gestureMap.json", 'w') as f:
                json.dump(test_gmap, f)

            # generate test data to emulate Training_Model.json
            test_data = [
                {"label": f"gesture_{i%3}", "features": np.random.rand(3).tolist()}
                for i in range(5)
            ]

            # create fake Training_Model.json to test script
            with open (temp_path / "Training_Model.json", 'w') as f:
                json.dump(test_data, f)

            # calculate scaler stats manually
            features = np.array([d["features"] for d in test_data])
            scaling = StandardScaler()
            features = scaling.fit_transform(features)
            compare_scaler_stats = {
                "mean": scaling.mean_.tolist(),
                "std": scaling.scale_.tolist()
            }

            # set the path to the Model_Training.py script directory
            base_directory = Path(__file__).parent

            # Run the Model_Training.py script
            subprocess.run([sys.executable, str(base_directory / "Dummy_Model_Training.py")], cwd=temp_path, check=True)

            # assert that "scaler_stats.json" was created
            self.assertTrue(test_htdocs / "scaler_stats.json")

            # load the test scaler stats from "scaler_stats.json"
            with open (test_htdocs / "scaler_stats.json", 'r') as f:
                test_stats = json.load(f)
            
            # Assertions
            print("==== Scaler Stats Test ====\n")
            self.assertIn("mean", test_stats)
            self.assertIn("std", test_stats)

if __name__ == "__main__":
    unittest.main()